class ACTIONTYPE {
  static CHANGE_STATUS_FIRSTTIME = 'CHANGE_FIRSTTIME';
  static UPDATE_USER = 'UPDATE_USER';
  static UPDATE_TARGET = 'UPDATE_TARGET';
  static UPDATE_TOKEN = 'UPDATE_TOKEN';
  static UPDATE_KONTAKLIST = 'UPDATE_KONTAKLIST';
}

export default ACTIONTYPE;
